server:
  port: 9700
spring:
  application:
    name: consumer-service
  redis:
    host: 192.168.2.125
    password: 123456
    port: 6379
    database: 0
    # 连接超时时间 单位 ms（毫秒）
    timeout: 3000
    jedis:
      pool:
        # 连接池中的最大空闲连接，默认值也是8。
        max-idle: 10
        max-active: 10
        # 等待可用连接的最大时间，单位毫秒，默认值为-1，表示永不超时
        max-wait: 1000
  rabbitmq:
    addresses: 192.168.2.125
    username: admin
    password: 123456
    virtual-host: myvhost
    connection-timeout: 15000
    port: 5672
    # 投递结果回调开关
    publisher-confirm-type: correlated
    # 未找到投递目标队列失败回调开关，比如RouteKey匹配不到目标队列
    publisher-returns: true
    cache:
      connection:
        mode: connection
        size: 5
      channel:
        size: 2
#eureka:
#  client:
#    service-url:
#      defaultZone: http://gallop:123456@localhost:10025/eureka/
#  instance:
#    instance-id: ${spring.cloud.client.ip-address}:${spring.application.name}:${server.port}

jwt:
  token-header: x-mch-user-token
  expire: 14400
  rsa-secret: xx1WET12^%3^(WE45