server:
  port: 9700
spring:
  application:
    name: consumer-service
  redis:
    host: 192.168.2.125
    password: 123456
    port: 6379
    database: 0
    # 连接超时时间 单位 ms（毫秒）
    timeout: 3000
    jedis:
      pool:
        # 连接池中的最大空闲连接，默认值也是8。
        max-idle: 10
        max-active: 10
        # 等待可用连接的最大时间，单位毫秒，默认值为-1，表示永不超时
        max-wait: 1000
eureka:
  client:
    service-url:
      defaultZone: http://gallop:123456@localhost:10025/eureka/
  instance:
    instance-id: ${spring.cloud.client.ip-address}:${spring.application.name}:${server.port}

jwt:
  token-header: x-mch-user-token
  expire: 14400
  rsa-secret: xx1WET12^%3^(WE45