server:
  port: 9999

#请求和响应GZIP压缩支持
feign:
  httpclient:
    enabled: false
  okhttp:
    enabled: true
  compression:
    request:
      enabled: true
      mime-types: text/xml,application/xml,application/json
      min-request-size: 2048
    response:
      enabled: true
spring:
  application:
    name: gateway-hystrix-service
  redis:
    host: 192.168.2.125
    password: 123456
    port: 6379
    database: 0
    # 连接超时时间 单位 ms（毫秒）
    timeout: 3000
    jedis:
      pool:
        # 连接池中的最大空闲连接，默认值也是8。
        max-idle: 10
        max-active: 10
        # 等待可用连接的最大时间，单位毫秒，默认值为-1，表示永不超时
        max-wait: 1000
  cloud:
    gateway:
      discovery:
        locator:
          # 路由的路径对应会使用大写ID，若想要使用小写ID,设为true
          lowerCaseServiceId: true
          # 自定义predicates Factory需要禁止gateway通过服务发现组件转发请求到其他的微服务
          # 启用了自动根据服务ID建立路由
          enabled: false
      routes:
        # =====================================
        - id: consumer-service
          uri: lb://consumer-service
          # order: 8000
          predicates:
            # 注意名称必须为路由谓词工厂类名的前缀，参数为允许访问的时间段
            - TimeBetween=上午8:00,下午11:50
            - Path=/api/consumer/**
          filters:
            # 名称必须为过滤器工厂类名的前缀，
            - name: TimeBetween
            - StripPrefix=2
            # redis限流 ， filter名称必须是RequestRateLimiter
            - name: RequestRateLimiter
              args:
                # 使用SpEL名称引用Bean，与上面新建的RateLimiterConfig类中的bean的name相同
                key-resolver: '#{@remoteAddrKeyResolver}'
                # 每秒最大访问次数
                redis-rate-limiter.replenishRate: 2
                # 令牌桶最大容量
                redis-rate-limiter.burstCapacity: 5
      default-filters:
        - name: Hystrix
          args:
            name: default
            fallbackUri: 'forward:/defaultfallback'


gate:
  ignore:
    startWith: /auth/jwt

auth:
  serviceId: consumer-service
  client:
    token-header: x-mch-client-token
  user:
    token-header: x-mch-user-token
# 注册中心
eureka:
  instance:
    #prefer-ip-address: true
    instance-id: ${spring.cloud.client.ip-address}:${spring.application.name}:${server.port}
  client:
    service-url:
      defaultZone: http://gallop:123456@localhost:10025/eureka/


hystrix:
  threadpool:
    default:
      coreSize: 1000 ##并发执行的最大线程数，默认10
      maxQueueSize: 1000 ##BlockingQueue的最大队列数
      queueSizeRejectionThreshold: 500 ##即使maxQueueSize没有达到，达到queueSizeRejectionThreshold该值后，请求也会被拒绝
  #hystrix 信号量隔离，1秒后自动超时返回
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 1000

# 打印网关日志信息
logging:
  level:
    org.springframework.cloud.gateway: error